### ISSUE TITLE
Task: Add reference button to lesson pages

### ISSUE THREAD

**Issue by coreyrop** [coreyrop/SMIP#26]
Add a button to lesson pages that give access to helpful resources for those learning MIPS, and some geared towards that specific lesson

**Comment by coreyrop** [comment]
# Task Test
1. Open SMIP
2. select start
3. find reference button

**Comment by animeshsoni** [comment]
Reference button on Main Menu works. Did not add it to the lessons page because we don't have a functioning lessons page yet.

**Comment by coreyrop** [comment]
implemented
