### ISSUE TITLE
Task: Move Green Sheet.jpg to a new folder and change relative path for image

### ISSUE THREAD

**Issue by animeshsoni** [coreyrop/SMIP#35]
Will need to convert relative path to absolute path for the os to recognize the image path. Using the os module for absolute paths.

**Comment by coreyrop** [comment]
# Task Test
1. check pdf is in specified folder
2. check that pdf still displays

**Comment by animeshsoni** [comment]
Added a new folder at the top level called References with Green Sheet jpeg. Used the os library to change relative paths to absolute and to join the paths.
