### ISSUE TITLE
Task: Lesson creation form styling

### ISSUE THREAD

**Issue by coreyrop** [coreyrop/SMIP#46]
Style the lesson creation form so that it is visual appealing and formatted in a way that is pleasant to use.

**Comment by coreyrop** [comment]
# Task Test
1. go to lesson creation form 
2. check that form looks properly spaced
3. check that form provides a pleasant customer experience

**Comment by cprowesl** [comment]
# Pass
This task test passes as satisfactory for form spacing and customer experience.
