### ISSUE TITLE
Task: Style Based on OS

### ISSUE THREAD

**Issue by coreyrop** [coreyrop/SMIP#57]
As a client, I would like a styling that works for my OS, colors in Tkinter function differently for MacOS and for Linux, so I would like to choose from color options that fit on my system.

**Comment by coreyrop** [comment]
# Task Test
1. Open SMIP
2. Go to Settings
3. Confirm Colors work on MacOS and on Linux

**Comment by cprowesl** [comment]
# Pass 
SMIP passes this task test.
