### ISSUE TITLE
Task: Save Client Selected Schemes

### ISSUE THREAD

**Issue by coreyrop** [coreyrop/SMIP#58]
As a client, I would like my selected color scheme to remain selected between sessions on the application.

**Comment by coreyrop** [comment]
# Task Test
1. Open SMIP
2. Go to Settings
3. Select a different color scheme
4. close SMIP
5. Reopen SMIP
6. Assure SMIP has your loaded color scheme

**Comment by cprowesl** [comment]
# Pass
SMIP passes this task test.
